name = "Blank"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE"
description = "Starter Hugo theme for developers."
homepage = "https://github.com/vimux/blank/"
demosite = "https://blank-demo.netlify.app/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Vimux"
  homepage = "https://github.com/vimux"
